name: asmscan-proteinbert
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.21
  - seaborn=0.12.2
  - umap-learn=0.5.4
  - pip=25.0
  - pip:
      - biopython==1.85
      - h5py==3.1.0
      - matplotlib==3.5.3
      - numba==0.56.4
      - numpy==1.19.5
      - pandas==1.2.5
      - scikit-learn==1.0.2
      - scipy==1.10.1
      - tensorflow==2.5.3
      - tqdm==4.66.6
