ALL_AMINO_ACIDS = 'ACDEFGHIKLMNPQRSTUVWXY'
SPECIAL_TOKENS = ['<OTHER>', '<START>', '<END>', '<PAD>']
EXTRA_TOKENS_PER_SEQUENCE = 2
MODEL_PATH = './models/'
DATA_PATH = './test_sets/'
SEQUENCE_LENGTH = 42
SEQUENCE_CUTOFF = 40